In [350]:
import torch 
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable
from torch.utils.data import Dataset, DataLoader


from dataset_mod import MyDataset_encoder, one_hot_targets


%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [259]:
Z_2 = torch.rand(1, 32, 16,16)
print(Z_2[:,:,15,15])
output, indices_max = F.max_pool2d_with_indices(Z_2, kernel_size=Z_2.size()[2:],
                                                               return_indices=True )
#output = output.view(-1, 32)
print(output.shape)
F.max_unpool2d(output, indices_max, kernel_size=2, stride=2, output_size=(1, 32, 16, 16))

tensor([[0.6765, 0.6573, 0.8925, 0.8322, 0.3559, 0.9032, 0.3732, 0.1610, 0.3530,
         0.9256, 0.2826, 0.9862, 0.5014, 0.7221, 0.3528, 0.7073, 0.6924, 0.8323,
         0.9745, 0.1472, 0.4280, 0.8703, 0.7935, 0.2447, 0.8994, 0.6831, 0.9750,
         0.3068, 0.4167, 0.0773, 0.8913, 0.1518]])
torch.Size([1, 32, 1, 1])


ValueError: invalid output_size "(16, 16)" (dim 0 must be between 0 and 4)

In [385]:
import numpy as np
outputs = torch.sigmoid(torch.rand(200, 10))
targets = torch.sigmoid(torch.rand(200, 10))
x = torch.topk(outputs,2,dim=1 )
y = torch.topk(targets,2,dim=1 )
outputs = x[1].numpy()
targets  = y[1].numpy()

accuracy = np.sum(outputs == targets)/outputs.size
accuracy


0.1025

In [394]:
input = torch.randn(3, 5, requires_grad=True)
target = torch.randint(5, (3,), dtype=torch.int64)
loss = F.cross_entropy(input, target)
#loss.backward()

In [399]:
input

tensor([[ 0.0166, -0.1305,  1.3678, -0.4145, -0.8255],
        [-0.4362, -0.2758,  0.4796,  1.2652, -0.9480],
        [ 0.1717,  0.1214,  1.0385, -0.4093, -0.2612]], requires_grad=True)

In [407]:
torch.max(F.log_softmax(input[0,:]),0)

/Users/riccardoconci/anaconda3/envs/compneuro/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


torch.return_types.max(
values=tensor(-0.5666, grad_fn=<MaxBackward0>),
indices=tensor(2))

In [430]:
y_hat = torch.rand(2,10)
y = torch.FloatTensor([[0,0,0,1,0,0,0,0,1,0], [0,0,0,1,0,0,0,0,1,0]])
y

tensor([[0., 0., 0., 1., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 1., 0.]])

In [431]:
y*torch.log(y_hat) 

tensor([[-0.0000, -0.0000, -0.0000, -1.2191, -0.0000, -0.0000, -0.0000, -0.0000,
         -1.6805, -0.0000],
        [-0.0000, -0.0000, -0.0000, -0.1705, -0.0000, -0.0000, -0.0000, -0.0000,
         -0.1083, -0.0000]])

In [432]:
torch.sum((1-y)*torch.log(1-y_hat))

tensor(-18.2146)

In [433]:
def categorical_CE_loss(y_hat, y):
    return(-torch.sum(y*torch.log(y_hat) + (1-y)*torch.log(1-y_hat)))
    

In [434]:
categorical_CE_loss(y_hat, y)

tensor(21.3931)