In [350]:
import torch 
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable
from torch.utils.data import Dataset, DataLoader


from dataset_mod import MyDataset_encoder, one_hot_targets


%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [259]:
Z_2 = torch.rand(1, 32, 16,16)
print(Z_2[:,:,15,15])
output, indices_max = F.max_pool2d_with_indices(Z_2, kernel_size=Z_2.size()[2:],
                                                               return_indices=True )
#output = output.view(-1, 32)
print(output.shape)
F.max_unpool2d(output, indices_max, kernel_size=2, stride=2, output_size=(1, 32, 16, 16))

tensor([[0.6765, 0.6573, 0.8925, 0.8322, 0.3559, 0.9032, 0.3732, 0.1610, 0.3530,
         0.9256, 0.2826, 0.9862, 0.5014, 0.7221, 0.3528, 0.7073, 0.6924, 0.8323,
         0.9745, 0.1472, 0.4280, 0.8703, 0.7935, 0.2447, 0.8994, 0.6831, 0.9750,
         0.3068, 0.4167, 0.0773, 0.8913, 0.1518]])
torch.Size([1, 32, 1, 1])


ValueError: invalid output_size "(16, 16)" (dim 0 must be between 0 and 4)

In [385]:
import numpy as np
outputs = torch.sigmoid(torch.rand(200, 10))
targets = torch.sigmoid(torch.rand(200, 10))
x = torch.topk(outputs,2,dim=1 )
y = torch.topk(targets,2,dim=1 )
outputs = x[1].numpy()
targets  = y[1].numpy()

accuracy = np.sum(outputs == targets)/outputs.size
accuracy


0.1025

In [394]:
input = torch.randn(3, 5, requires_grad=True)
target = torch.randint(5, (3,), dtype=torch.int64)
loss = F.cross_entropy(input, target)
#loss.backward()

In [399]:
input

tensor([[ 0.0166, -0.1305,  1.3678, -0.4145, -0.8255],
        [-0.4362, -0.2758,  0.4796,  1.2652, -0.9480],
        [ 0.1717,  0.1214,  1.0385, -0.4093, -0.2612]], requires_grad=True)

In [407]:
torch.max(F.log_softmax(input[0,:]),0)

/Users/riccardoconci/anaconda3/envs/compneuro/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


torch.return_types.max(
values=tensor(-0.5666, grad_fn=<MaxBackward0>),
indices=tensor(2))

In [448]:
y_hat = torch.FloatTensor([[0,1,0,0,0,1,0,0,0,0], [1,0,0,1,0,0,0,0,0,0]])
y = y_hat#torch.FloatTensor([[0,0,0,1,0,0,0,0,1,0], [0,0,0,1,0,0,0,0,1,0]])
y
e = 1e-20

In [446]:
def categorical_CE_loss(y_hat, y):
    return(-torch.sum(y*torch.log(y_hat+e) + (1-y)*torch.log(1-y_hat+e)))
    

In [449]:
categorical_CE_loss(y_hat, y)

tensor(-0.)

In [455]:
x=torch.tensor(-1.3)

In [456]:
torch.sigmoid(x)

tensor(0.2142)

In [461]:
lr=0.1
epoch=100

lr * (0.1 ** (epoch/40))

0.000316227766016838

In [1]:
from dataset_sup import MyDataset_encoder
import os

In [ ]:
/Users/riccardoconci/Desktop/2_dig_fixed_random_bw/digts/train/orig/orig_0.bmp

In [13]:
dset_dir= "/Users/riccardoconci/Desktop/2_dig_fixed_random_bw/digts/"
image_paths = "{}train/orig/".format(dset_dir)
target_paths = "{}digts.csv".format(dset_dir)
image_paths
#os.listdir(image_paths)
files = [image_paths+ 'orig_{}'.format(i) for i in range(len(os.listdir(image_paths)))]
#files.sort(key=lambda x: os.path.getmtime(x))
files

['/Users/riccardoconci/Desktop/2_dig_fixed_random_bw/digts/train/orig/orig_0',
 '/Users/riccardoconci/Desktop/2_dig_fixed_random_bw/digts/train/orig/orig_1',
 '/Users/riccardoconci/Desktop/2_dig_fixed_random_bw/digts/train/orig/orig_2',
 '/Users/riccardoconci/Desktop/2_dig_fixed_random_bw/digts/train/orig/orig_3',
 '/Users/riccardoconci/Desktop/2_dig_fixed_random_bw/digts/train/orig/orig_4',
 '/Users/riccardoconci/Desktop/2_dig_fixed_random_bw/digts/train/orig/orig_5',
 '/Users/riccardoconci/Desktop/2_dig_fixed_random_bw/digts/train/orig/orig_6',
 '/Users/riccardoconci/Desktop/2_dig_fixed_random_bw/digts/train/orig/orig_7',
 '/Users/riccardoconci/Desktop/2_dig_fixed_random_bw/digts/train/orig/orig_8',
 '/Users/riccardoconci/Desktop/2_dig_fixed_random_bw/digts/train/orig/orig_9',
 '/Users/riccardoconci/Desktop/2_dig_fixed_random_bw/digts/train/orig/orig_10',
 '/Users/riccardoconci/Desktop/2_dig_fixed_random_bw/digts/train/orig/orig_11',
 '/Users/riccardoconci/Desktop/2_dig_fixed_random_

In [ ]:
dset_train = MyDataset_encoder
train_kwargs = {'image_paths':train_image_paths,
                'target_paths': train_target_paths,
                'image_size': image_size, 
                'encoder_target_type':encoder_target_type,
                'train_test': 'train'}

train_data = dset_train(**train_kwargs) 

In [2]:
o = 32
w = 32
k =3
s=1
p= ((o-1)*s -w +k)/2
p

1.0

In [147]:
import torch
import numpy as np
from models.BLT_models import BLT_SB_decoder, spatial_broadcast_decoder

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [148]:
sbd_model = spatial_broadcast_decoder()

In [150]:
z  = torch.FloatTensor((1,2,3,4,5))
z = z.unsqueeze(0)
z_b = sbd_model(z)
z_b.shape


#z = z.repeat(h,w,1).view(z.size(0), z.size(1),h,w)

torch.Size([1, 7, 32, 32])

In [162]:
import random
random.randint(0,21)

20

In [161]:
z.repeat(10,10).shape

torch.Size([10, 50])

In [97]:
z[0,:,:,:]

tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4,  5,

In [64]:
z  = torch.ones(5,20)


torch.Size([5, 22, 32, 32])
torch.Size([1, 32, 32])
torch.Size([32, 160, 20])


RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 2. Got 32 and 1 in dimension 0 at /Users/distiller/project/conda/conda-bld/pytorch_1556653464916/work/aten/src/TH/generic/THTensor.cpp:711

In [68]:
x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
x.shape

(2, 2, 2)

In [47]:
z_b = z_b.unsqueeze(0)
z_b.shape


torch.Size([1, 32, 32, 22])

In [48]:
decoder = BLT_SB_decoder(20,0,1)

In [49]:
img = decoder(z_b)

RuntimeError: Given groups=1, weight of size 64 22 3 3, expected input[1, 32, 32, 22] to have 22 channels, but got 32 channels instead

In [14]:
z  = torch.rand(1,5)
h = 32; w = 32
z_b = z.repeat(h, w)
z_b.shape

torch.Size([32, 160])